### ISSUE TITLE
Footprint/Library missing

### ISSUE THREAD

**Issue by lienbacher** [pauls-3d-things/ttgo-32-micro-breakout-board#1]
Hey Paul!
I noticed you only included KiCad Project without Library and footprint of the component.
Any chance you could publish those as well?

**Comment by uvwxy** [comment]
https://github.com/pauls-3d-things/kicad-library/blob/master/footprints.pretty/ttgo-32-micro.kicad_mod

... I should do better documentation where I keep my stuff 😅
